[package]
name = "tmn"
version = "0.1.4"
edition = "2021"
license = "MIT"
authors = ["Operator 415D"]
description = "Instrument for working with complex numbers and quaternions"

[profile.dev]
opt-level = 0

[dependencies]
